version: '3.9'

services:
  db:
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=database
    image: bitnami/mongodb:5.0.5-debian-10-r16
    networks:
      - db-net
    volumes:
      - db-data:/bitnami/mongodb

  graph-generator:
    build: ./graph-generator
    environment:
      - COMMUNICATION_SERVER_DOMAIN=cs_entrypoint
      - PORT=8000
      - RELOAD=False
    image: madpeh/sre-graph-generator
    networks:
      - graph-generator-net

  redis:
    environment:
      - REDIS_PASSWORD=password
    image: bitnami/redis:6.2.6-debian-10-r92
    networks:
      - redis-net
    volumes:
      - redis-data:/bitnami/redis

  simulation-load-balancer:
    build: ./simulation-load-balancer
    environment:
      - GRAPH_GENERATOR_URL=http://graph-generator:8000
      - LOG_LEVEL_HANDLERS=INFO
      - PORT=8000
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - RELOAD=False
      - TRANSLATOR_URL=http://translator:8000
    image: madpeh/sre-simulation-load-balancer
    networks:
      - graph-generator-net
      - redis-net
      - spade-instance-net
      - translator-net
    ports:
      - "80:8000"

  spade-instance:
    environment:
      - ACTIVE_SIMULATION_STATUS_ANNOUCEMENT_URL=http://127.0.0.1:8000/internal/instance/status
      - ACTIVE_SIMULATION_STATUS_ANNOUCEMENT_PERIOD=10
      - AGENT_BACKUP_URL=http://127.0.0.1:8000/internal/simulation/agent_data
      - AGENT_BACKUP_PERIOD=15
      - AGENT_BACKUP_DELAY=5
      - AGENT_REGISTRATION_MAX_CONCURRENCY=10
      - AGENT_REGISTRATION_RETRY_AFTER=5
      - API_BACKUP_URL=http://simulation-load-balancer:8000
      - COMMUNICATION_SERVER_PASSWORD=password
      - LOG_LEVEL_AGENT=INFO
      - LOG_LEVEL_HANDLERS=INFO
      - LOG_LEVEL_UVICORN_ACCESS=WARNING
      - LOG_LEVEL_ROUTERS=INFO
      - LOG_LEVEL_SIMULATION_CODE_GENERATION=INFO
      - LOG_LEVEL_SIMULATION_INITIALIZATION=INFO
      - LOG_LEVEL_SIMULATION_MAIN=INFO
      - LOG_LEVEL_SIMULATION_STATUS=INFO
      - LOG_LEVEL_SPADE_BEHAVIOUR=WARNING
      - LOG_LEVEL_STATE=INFO
      - PORT=8000
      - RELOAD=False
      - SIMULATION_LOAD_BALANCER_URL=http://simulation-load-balancer:8000
      - SIMULATION_LOAD_BALANCER_ANNOUNCEMENT_PERIOD=10
      - SIMULATION_PROCESS_HEALTH_CHECK_PERIOD=5
    image: madpeh/sre-spade-instance
    networks:
      - spade-instance-net
      - external-sre-cs-network

  translator:
    build: ./translator
    environment:
      - PORT=8000
      - RELOAD=False
    image: madpeh/sre-translator
    networks:
      - translator-net

networks:
  db-net:
  graph-generator-net:
  redis-net:
  spade-instance-net:
  translator-net:
  external-sre-cs-network:
    external: true
    name: sre-cs

volumes:
  db-data:
  redis-data:
