version: '3.9'

services:
  db:
    container_name: db-dev
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=database
    expose:
      - 27017
    image: bitnami/mongodb:5.0.5-debian-10-r16
    networks:
      - db-net
    ports:
      - "27017:27017"
    restart: "no"
    volumes:
      - db-data:/bitnami/mongodb

  db-gui:
    container_name: db-gui-dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_OPTIONS_EDITORTHEME=3024-night
    image: mongo-express:0.54.0
    networks:
      - db-net
    ports:
      - "27018:8081"
    restart: "no"

  graph-generator:
    build: ./graph-generator
    container_name: graph-generator-dev
    environment:
      - COMMUNICATION_SERVER_DOMAIN=agents-sim.xyz
      - PORT=8000
      - RELOAD=True
    expose:
      - 8000
    networks:
      - graph-generator-net
    ports:
      - "8001:8000"
    restart: "no"
    volumes:
      - ./graph-generator/src:/api/src

  simulation-load-balancer:
    build: ./simulation-load-balancer
    container_name: simulation-load-balancer-dev
    environment:
      - DB_URL=mongodb://user:pass@db:27017/database
      - GRAPH_GENERATOR_URL=http://graph-generator:8000
      - PORT=8000
      - RELOAD=True
      - TRANSLATOR_URL=http://translator:8000
    expose:
      - 8000
    networks:
      - db-net
      - graph-generator-net
      - translator-net
    ports:
      - "80:8000"
    restart: "no"
    volumes:
      - ./simulation-load-balancer/src:/api/src

  translator:
    build: ./translator
    container_name: translator-dev
    environment:
      - PORT=8000
      - RELOAD=True
    expose: 
      - 8000
    networks:
      - translator-net
    ports:
      - "8000:8000"
    restart: "no"
    volumes:
      - ./translator/src:/api/src

networks:
  db-net:
  graph-generator-net:
  translator-net:

volumes:
  db-data:
