version: '3.9'

services:
  db:
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=database
    image: bitnami/mongodb:5.0.5-debian-10-r16
    networks:
      - db-net
    ports:
      - "27017:27017"
    volumes:
      - db-data:/bitnami/mongodb

  db-gui:
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_OPTIONS_EDITORTHEME=3024-night
    image: mongo-express:0.54.0
    networks:
      - db-net
    ports:
      - "27018:8081"

  graph-generator:
    build: ./graph-generator
    environment:
      - COMMUNICATION_SERVER_DOMAIN=cs_entrypoint
      - PORT=8000
      - RELOAD=True
    image: 127.0.0.1:5000/graph-generator
    networks:
      - graph-generator-net
    ports:
      - "8001:8000"
    volumes:
      - ./graph-generator/src:/api/src

  simulation-load-balancer:
    build: ./simulation-load-balancer
    environment:
      - DB_URL=mongodb://user:pass@db:27017/database
      - GRAPH_GENERATOR_URL=http://graph-generator:8000
      - PORT=8000
      - RELOAD=True
      - TRANSLATOR_URL=http://translator:8000
    image: 127.0.0.1:5000/simulation-load-balancer
    networks:
      - db-net
      - graph-generator-net
      - spade-instance-net
      - translator-net
    ports:
      - "80:8000"
    volumes:
      - ./simulation-load-balancer/src:/api/src

  spade-instance:
    build: ./spade-instance
    environment:
      - AGENT_BACKUP_URL=http://localhost:8000/simulation/agent_data
      - API_BACKUP_URL=http://simulation-load-balancer:8000
      - BACKUP_PERIOD=15
      - BACKUP_DELAY=5
      - COMMUNICATION_SERVER_PASSWORD=password
      - INSTANCE_STATUS_URL=http://localhost:8000/instance/status
      - LOG_LEVEL_HANDLERS=INFO
      - LOG_LEVEL_UVICORN_ACCESS=WARNING
      - LOG_LEVEL_ROUTERS=INFO
      - LOG_LEVEL_SIMULATION=INFO
      - LOG_LEVEL_STATE=INFO
      - PORT=8000
      - PROCESS_VERIFICATION_PERIOD=5
      - RETRY_REGISTRATION_PERIOD=5
      - RELOAD=True
      - SIMULATION_LOAD_BALANCER_URL=http://simulation-load-balancer:8000
      - SIMULATION_LOAD_BALANCER_ANNOUNCEMENT_PERIOD=10
    image: 127.0.0.1:5000/spade-instance
    networks:
      - spade-instance-net
      - external-sre-cs-net
    volumes:
      - ./spade-instance/src:/api/src

  translator:
    build: ./translator
    environment:
      - PORT=8000
      - RELOAD=True
    image: 127.0.0.1:5000/translator
    networks:
      - translator-net
    ports:
      - "8000:8000"
    volumes:
      - ./translator/src:/api/src

networks:
  db-net:
  graph-generator-net:
  spade-instance-net:
  translator-net:
  external-sre-cs-net:
    external: true
    name: sre-cs

volumes:
  db-data:
