version: '3.9'

services:
  data-processor:
    build:
      context: ./data-processor
      dockerfile: Dockerfile.test
    container_name: data-processor-test
    restart: "no"

  graph-generator:
    build:
      context: ./graph-generator
      dockerfile: Dockerfile.test
    container_name: graph-generator-test
    restart: "no"

  kafka-consumer:
    build:
      context: ./kafka-consumer
      dockerfile: Dockerfile.test
    container_name: kafka-consumer-test
    restart: "no"

  simulation-load-balancer:
    build:
      context: ./simulation-load-balancer
      dockerfile: Dockerfile.test
    container_name: simulation-load-balancer-test
    restart: "no"

  spade-instance:
    build:
      context: ./spade-instance
      dockerfile: Dockerfile.test
    container_name: spade-instance-test
    restart: "no"

  translator:
    build:
      context: ./translator
      dockerfile: Dockerfile.test
    container_name: translator-test
    restart: "no"
