version: '3.9'

services:
  data-processor:
    build: ./data-processor
    environment:
      - DB_URL=neo4j://db:7687
      - LOG_LEVEL_SERVICES=INFO
      - PORT=8000
      - PROXY_REGISTRATION_ADDRESS=data-processor-proxy:5555
      - PROXY_REGISTRATION_BACKEND_DATA_PROCESSOR_NAME=data_processor
      - PROXY_REGISTRATION_BACKEND_DATA_PROCESSOR_PORT=8000
      - PROXY_REGISTRATION_MAX_RETRIES=100
      - PROXY_REGISTRATION_USER_NAME=admin
      - PROXY_REGISTRATION_USER_PASSWORD=admin
      - RELOAD=False
      - WAIT_FOR_DB_ADDRESS=db:7474
      - WAIT_FOR_PROXY_ADDRESS=data-processor-proxy:5555
    image: "madpeh/sre-data-processor:${VERSION}"
    networks:
      - data-processor-proxy-net
      - db-net

  data-processor-proxy:
    build: ./data-processor-proxy
    environment:
      - API_PORT=5555
      - DATA_PROCESSOR_LISTEN_PORT=8000
    image: "madpeh/sre-data-processor-proxy:${VERSION}"
    networks:
      - data-processor-proxy-net
      - entrypoint-net
    volumes:
      - data-processor-proxy-data:/usr/local/etc/haproxy

  db:
    environment:
      - NEO4J_AUTH=none
      - NEO4JLABS_PLUGINS=["apoc"]
    image: neo4j:4.4.2-community
    networks:
      - db-net
      - entrypoint-net
    volumes:
      - db-data:/data

  entrypoint:
    build: ./entrypoint
    environment:
      - API_LISTEN_PORT=80
      - DATA_PROCESSOR_PROXY_BACKEND_PORT=8000
      - DB_LISTEN_PORT=7687
      - DB_BACKEND_PORT=7687
      - SIMULATION_LOAD_BALANCER_BACKEND_PORT=8000
    image: "madpeh/sre-entrypoint:${VERSION}"
    networks:
      - entrypoint-net
      - external-li-sre-net
    volumes:
      - entrypoint-data:/usr/local/etc/haproxy

  graph-generator:
    build: ./graph-generator
    environment:
      - COMMUNICATION_SERVER_DOMAIN=cs_entrypoint
      - PORT=8000
      - RELOAD=False
    image: "madpeh/sre-graph-generator:${VERSION}"
    networks:
      - graph-generator-net

  kafka:
    build: ./kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_OFFSET_METADATA_MAX_BYTES=10485760
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - WAIT_FOR_ZOOKEEPER_ADDRESS=zookeeper:2181
    image: "madpeh/sre-kafka:${VERSION}"
    networks:
      - kafka-net
      - zookeeper-net
    volumes:
      - ./kafka/startup_scripts:/docker-entrypoint-initdb.d
      - kafka-data:/bitnami/kafka

  kafka-consumer:
    build: ./kafka-consumer
    environment:
      - BATCH_TIMEOUT_MS=5000
      - DB_URL=neo4j://db:7687
      - KAFKA_ADDRESS=kafka:9092
      - LOG_LEVEL_MAIN=INFO
      - UPDATE_AGENT_OUTPUT_TOPIC_NAME=update_agent_output
      - WAIT_FOR_DB_ADDRESS=db:7474
      - WAIT_FOR_KAFKA_ADDRESS=kafka:9092
      - WAIT_FOR_KAFKA_TOPICS=update_agent_output
    image: "madpeh/sre-kafka-consumer:${VERSION}"
    networks:
      - db-net
      - kafka-net

  kafka-consumer-mongo:
    build: ./kafka-consumer-mongo
    environment:
      - BATCH_TIMEOUT_MS=5000
      - DB_URL=mongodb://user:pass@mongo:27017/simulations
      - KAFKA_ADDRESS=kafka:9092
      - LOG_LEVEL_MAIN=INFO
      - UPDATE_AGENT_INPUT_TOPIC_NAME=update_agent_input
      - WAIT_FOR_DB_ADDRESS=mongo:27017
      - WAIT_FOR_KAFKA_ADDRESS=kafka:9092
      - WAIT_FOR_KAFKA_TOPICS=update_agent_input
    image: "madpeh/sre-kafka-consumer-mongo:${VERSION}"
    networks:
      - mongo-net
      - kafka-net

  kafka-streams:
    build: ./kafka-streams
    environment:
      - BOOTSTRAP_SERVER=kafka:9092
      - UPDATE_AGENT_INPUT_TOPIC_NAME=update_agent_input
      - UPDATE_AGENT_OUTPUT_TOPIC_NAME=update_agent_output
      - WAIT_FOR_KAFKA_ADDRESS=kafka:9092
      - WAIT_FOR_KAFKA_TOPICS=update_agent_input,update_agent_output
    image: "madpeh/sre-kafka-streams:${VERSION}"
    networks:
      - kafka-net

  kafka-topic-creator:
    build: ./kafka-topic-creator
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - BOOTSTRAP_SERVER=kafka:9092
      - NUM_BROKERS=1
      - UPDATE_AGENT_INPUT_TOPIC_NAME=update_agent_input
      - UPDATE_AGENT_INPUT_TOPIC_REPLICATION_FACTOR=1
      - UPDATE_AGENT_INPUT_TOPIC_PARTITIONS=1
      - UPDATE_AGENT_OUTPUT_TOPIC_NAME=update_agent_output
      - UPDATE_AGENT_OUTPUT_TOPIC_REPLICATION_FACTOR=1
      - UPDATE_AGENT_OUTPUT_TOPIC_PARTITIONS=1
      - WAIT_FOR_KAFKA_ADDRESS=kafka:9092
      - WAIT_FOR_ZOOKEEPER_ADDRESS=zookeeper:2181
      - ZOOKEEPER_SERVER=zookeeper:2181
    image: "madpeh/sre-kafka-topic-creator:${VERSION}"
    networks:
      - kafka-net
      - zookeeper-net

  mongo:
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=pass
      - MONGODB_DATABASE=simulations
    image: bitnami/mongodb:5.0.8-debian-10-r10
    networks:
      - mongo-net
    volumes:
      - mongo-data:/bitnami/mongodb

  redis:
    environment:
      - REDIS_PASSWORD=password
    image: bitnami/redis:6.2.6-debian-10-r92
    networks:
      - redis-net
    volumes:
      - redis-data:/bitnami/redis

  simulation-load-balancer:
    build: ./simulation-load-balancer
    environment:
      - GRAPH_GENERATOR_URL=http://graph-generator:8000
      - DATA_PROCESSOR_URL=http://data-processor-proxy:8000
      - LOG_LEVEL_HANDLERS=INFO
      - PORT=8000
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - RELOAD=False
      - TRANSLATOR_URL=http://translator:8000
      - WAIT_FOR_REDIS_ADDRESS=redis:6379
    image: "madpeh/sre-simulation-load-balancer:${VERSION}"
    networks:
      - data-processor-proxy-net
      - entrypoint-net
      - graph-generator-net
      - redis-net
      - spade-instance-net
      - translator-net

  spade-instance:
    build: ./spade-instance
    environment:
      - ACTIVE_SIMULATION_STATUS_ANNOUCEMENT_URL=http://127.0.0.1:8000/internal/instance/status
      - ACTIVE_SIMULATION_STATUS_ANNOUCEMENT_PERIOD=10
      - AGENT_BACKUP_URL=http://127.0.0.1:8000/internal/simulation/agent_data
      - AGENT_BACKUP_PERIOD=15
      - AGENT_BACKUP_DELAY=5
      - AGENT_REGISTRATION_MAX_CONCURRENCY=10
      - AGENT_REGISTRATION_RETRY_AFTER=5
      - COMMUNICATION_SERVER_PASSWORD=password
      - KAFKA_ADDRESS=kafka:9092
      - KAFKA_UPDATE_AGENT_INPUT_TOPIC_NAME=update_agent_input
      - LOG_LEVEL_AGENT=INFO
      - LOG_LEVEL_KAFKA=INFO
      - LOG_LEVEL_UVICORN_ACCESS=WARNING
      - LOG_LEVEL_REPEATED_TASKS=INFO
      - LOG_LEVEL_ROUTERS=INFO
      - LOG_LEVEL_SIMULATION_CODE_GENERATION=INFO
      - LOG_LEVEL_SIMULATION_INITIALIZATION=INFO
      - LOG_LEVEL_SIMULATION_MAIN=INFO
      - LOG_LEVEL_SIMULATION_STATUS=INFO
      - LOG_LEVEL_SPADE_BEHAVIOUR=WARNING
      - LOG_LEVEL_STATE=INFO
      - PORT=8000
      - RELOAD=False
      - SIMULATION_LOAD_BALANCER_URL=http://simulation-load-balancer:8000
      - SIMULATION_LOAD_BALANCER_ANNOUNCEMENT_PERIOD=10
      - SIMULATION_PROCESS_HEALTH_CHECK_PERIOD=5
      - WAIT_FOR_KAFKA_ADDRESS=kafka:9092
      - WAIT_FOR_KAFKA_TOPICS=update_agent_input
    image: "madpeh/sre-spade-instance:${VERSION}"
    networks:
      - kafka-net
      - spade-instance-net
      - external-sre-cs-net

  translator:
    build: ./translator
    environment:
      - PORT=8000
      - RELOAD=False
    image: "madpeh/sre-translator:${VERSION}"
    networks:
      - translator-net

  zookeeper:
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    image: bitnami/zookeeper:3.7.0-debian-10-r259
    networks:
      - zookeeper-net
    volumes:
      - zookeeper-data:/bitnami/zookeeper

networks:
  data-processor-proxy-net:
  db-net:
  entrypoint-net:
  graph-generator-net:
  kafka-net:
  kafka-connect-net:
  mongo-net:
  redis-net:
  spade-instance-net:
  translator-net:
  zookeeper-net:
  external-sre-cs-net:
    external: true
    name: sre-cs
  external-li-sre-net:
    external: true
    name: li-sre

volumes:
  data-processor-proxy-data:
  db-data:
  entrypoint-data:
  kafka-data:
  kafka-connect-data:
  mongo-data:
  redis-data:
  zookeeper-data:
