version: '3.9'

services:
  data-processor:
    build: ./data-processor
    environment:
      - DB_URL=mongodb://user:pass@db:27017/simulations?authSource=admin
      - PORT=8000
      - RELOAD=True
    image: 127.0.0.1:5000/data-processor
    networks:
      - data-processor-net
      - db-net
    ports:
      - "8002:8000"
    volumes:
      - ./data-processor/src:/api/src


  db:
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
    image: bitnami/mongodb:5.0.5-debian-10-r16
    networks:
      - db-net
    ports:
      - "27017:27017"
    volumes:
      - db-data:/bitnami/mongodb

  db-gui:
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_OPTIONS_EDITORTHEME=3024-night
    image: mongo-express:0.54.0
    networks:
      - db-net
    ports:
      - "27018:8081"

  graph-generator:
    build: ./graph-generator
    environment:
      - COMMUNICATION_SERVER_DOMAIN=cs_entrypoint
      - PORT=8000
      - RELOAD=True
    image: 127.0.0.1:5000/graph-generator
    networks:
      - graph-generator-net
    ports:
      - "8001:8000"
    volumes:
      - ./graph-generator/src:/api/src

  redis:
    environment:
      - REDIS_PASSWORD=password
    image: bitnami/redis:6.2.6-debian-10-r92
    networks:
      - redis-net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/bitnami/redis

  simulation-load-balancer:
    build: ./simulation-load-balancer
    environment:
      - GRAPH_GENERATOR_URL=http://graph-generator:8000
      - LOG_LEVEL_HANDLERS=INFO
      - PORT=8000
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - RELOAD=True
      - TRANSLATOR_URL=http://translator:8000
    image: 127.0.0.1:5000/simulation-load-balancer
    networks:
      - data-processor-net
      - graph-generator-net
      - redis-net
      - spade-instance-net
      - translator-net
    ports:
      - "80:8000"
    volumes:
      - ./simulation-load-balancer/src:/api/src

  spade-instance:
    build: ./spade-instance
    environment:
      - ACTIVE_SIMULATION_STATUS_ANNOUCEMENT_URL=http://127.0.0.1:8000/internal/instance/status
      - ACTIVE_SIMULATION_STATUS_ANNOUCEMENT_PERIOD=10
      - AGENT_BACKUP_URL=http://127.0.0.1:8000/internal/simulation/agent_data
      - AGENT_BACKUP_PERIOD=15
      - AGENT_BACKUP_DELAY=5
      - AGENT_REGISTRATION_MAX_CONCURRENCY=10
      - AGENT_REGISTRATION_RETRY_AFTER=5
      - API_BACKUP_URL=http://simulation-load-balancer:8000
      - COMMUNICATION_SERVER_PASSWORD=password
      - LOG_LEVEL_AGENT=INFO
      - LOG_LEVEL_HANDLERS=INFO
      - LOG_LEVEL_UVICORN_ACCESS=WARNING
      - LOG_LEVEL_ROUTERS=INFO
      - LOG_LEVEL_SIMULATION_CODE_GENERATION=INFO
      - LOG_LEVEL_SIMULATION_INITIALIZATION=INFO
      - LOG_LEVEL_SIMULATION_MAIN=INFO
      - LOG_LEVEL_SIMULATION_STATUS=INFO
      - LOG_LEVEL_SPADE_BEHAVIOUR=WARNING
      - LOG_LEVEL_STATE=INFO
      - PORT=8000
      - RELOAD=True
      - SIMULATION_LOAD_BALANCER_URL=http://simulation-load-balancer:8000
      - SIMULATION_LOAD_BALANCER_ANNOUNCEMENT_PERIOD=10
      - SIMULATION_PROCESS_HEALTH_CHECK_PERIOD=5
    image: 127.0.0.1:5000/spade-instance
    networks:
      - data-processor-net
      - spade-instance-net
      - external-sre-cs-net
    volumes:
      - ./spade-instance/src:/api/src

  translator:
    build: ./translator
    environment:
      - PORT=8000
      - RELOAD=True
    image: 127.0.0.1:5000/translator
    networks:
      - translator-net
    ports:
      - "8000:8000"
    volumes:
      - ./translator/src:/api/src

networks:
  data-processor-net:
  db-net:
  graph-generator-net:
  redis-net:
  spade-instance-net:
  translator-net:
  external-sre-cs-net:
    external: true
    name: sre-cs

volumes:
  db-data:
  redis-data:
